AZURE_OPENAI_API_KEY="ca48cf88888441899bfd469aed24ec5c"
AZURE_OPENAI_ENDPOINT_CHAT="https://azureopenaistudio-dyi2023uc1.openai.azure.com/openai/deployments/DYIPOC/chat/completions?api-version=2023-07-01-preview"
AZURE_OPENAI_ENDPOINT_SUMMARY="https://azureopenaistudio-dyi2023uc1.openai.azure.com/openai/deployments/DYIPOC/completions?api-version=2023-09-15-preview"
AZURE_OPENAI_ENDPOINT_NLP_TO_PYTHON="https://azureopenaistudio-dyi2023uc1.openai.azure.com/openai/deployments/DYIPOC/completions?api-version=2023-09-15-preview"
openai.api_key ="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"